jobs:
    include:
        - language: java
          jdk: openjdk11
          sudo: true
          script:
              - cd bridge
              - mvn clean
              - mvn install -DskipTests
              - mvn package -DskipTests
              - mvn test
          after_success:
              - cd bridge
              - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report

        - language: node_js
          node_js: 12
          script:
              - cd viewer
              - npm install
              - npm run build && npm run copy & npm run pkg && npm run zip-bundle && rd /s /q ..\build\silovi-viewer && npm run build && npm run copy & npm run copy-dist && npm run zip
